### PR TITLE
add imagespath as a parameter

### PR DESCRIPTION
**Pull request by bear**
first pass at a fix for issue #2

### CODE REVIEW

**Comment by winfried** [comment]
On 09-07-15 02:58, Mike Taylor wrote:

Mike,

I won't have time to check / merge this pull request (and the older one
of Sam). But I don't mind if you do so. (At first look, it looks
sensible to me)

Winfried

**Comment by linuxwolf** [comment]
A couple of question/suggestions:
- Would it be sensible to include a default "images" directory in this project, and use that?
- Would it be possible to look at an environment variable or config file?

Speaking as an Editor member, I'm perfectly happy to specify these when running on the production box, but have something that "just works" out of the box.

**Comment by bear** [comment]
I would like to have a config file that specifies data and resource dirs and then also have command line params that override them - this gives us a lot of flexibility with little code overhead

**Comment by linuxwolf** [comment]
+1, especially if we can have some sensible defaults that work right away.

**I** think it makes sense to package the default resources in this project, but would be fine if those defaults are packaged into the "xeps" project.

**Comment by imaginator** [comment]
+1 on default resources that are packaged in this repo. Let's not overcomplicate things here!

**Comment by winfried** [comment]
On the parameters: for each parameter the script first looks at the commandline arguments, if not present at the config file, if not present it reverts to a sensible default. If the defaults can be better, please let me know (or fix it yourself ;-) ).

On including resources: first of all what resources are you talking about? Images, logo's and xsl sheets or tex dependencies? I think it would more logical to include the images, logo's and xsl sheets in the xeps repository, they inherently belong to them, regardless of the tool you use for building the xeps. Including the tex dependencies would be duplicating lots of code that available and packaged elsewhere. I see no reason to duplicate that work.

**Pull request merged**
