### PR TITLE
Make xeputils usable on python3

### PR DESCRIPTION
**Pull request by linkmauve**

### CODE REVIEW

**Comment by bear** [comment]
as long as we are ok (and maybe even mention this in the readme someplace) that xeputils is now 2.7+ only for python i'm +1

**Comment by linkmauve** [comment]
Added such a mention, I’m not sure about the minimum 3.x version we want to support and I can only test on 3.5 currently, I went for the oldest still maintained one but I’d be fine with requiring a newer version if we ever need anything from it.

**Comment by bear** [comment]
3.x is the latest version, so keeping it as current as possible is better IMO

+1 to merge IMO

**Comment by linkmauve** [comment]
Added a comment about a python2 path, and removed a superfluous `str()` in XEP.pprint.

This should now be good to merge.

**Pull request closed without merging**
